micronaut:
  # this config added to help debug
  http:
    client:
      timeout: 10m
  server:
    idle-timeout: 10m
  # end of debug timeout configs
  application:
    name: mnStockBroker2
  security:
    authentication: bearer
  token:
    jwt:
      signatures:
        secret:
          generator:
            secret: changeThisSecret
hello:
  world:
    message: "Hello from application.yml"
    translation:
      gr: "Καλημέρα κόσμε"
      en: "Hello world"
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-brocker`}
      user: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD:secret} #secret
      schemas: mn
      default-schema: mn
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-brocker`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:secret} #secret
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
# micronaut-data-jpa
jpa:
  default:
    entity-scan:
      packages: "com.hassialis.philip.broker.persistence"
    properties:
      hibernate:
        show_sql: false
