micronaut:
  # this config added to help debug
  http:
    client:
      timeout: 10m
  server:
    idle-timeout: 10m
  # end of debug timeout configs
  application:
    name: mnStockBroker2
  security:
    authentication: bearer
  token:
    jwt:
      signatures:
        secret:
          generator:
            secret: changeThisSecret
hello:
  world:
    message: "Hello from application.yml"
    translation:
      gr: "Καλημέρα κόσμε"
      en: "Hello world"
