micronaut:
  application:
    name: mnStockBroker2
  security:
    authentication: bearer
  token:
    jwt:
      signatures:
        secret:
          generator:
            secret: changeThisSecret
hello:
  world:
    message: "Hello from application.yml"
    translation:
      gr: "Καλημέρα κόσμε"
      en: "Hello world"
